flat_diet_study.Rmd:
  path: dev/flat_diet_study.Rmd
  state: active
  R:
  - R/distri_diet.R
  - R/get_res_diet.R
  - R/list_grp.R
  tests:
  - tests/testthat/test-list_grp.R
  - tests/testthat/test-distri_diet.R
  - tests/testthat/test-get_res_diet.R
  vignettes: []
  inflate:
    flat_file: dev/flat_diet_study.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_distri_diet.Rmd:
  path: dev/flat_distri_diet.Rmd
  state: active
  R:
  - R/distri_diet.R
  - R/get_res_diet.R
  - R/list_grp.R
  tests:
  - tests/testthat/test-list_grp.R
  - tests/testthat/test-distri_diet.R
  - tests/testthat/test-get_res_diet.R
  vignettes: []
  inflate:
    flat_file: dev/flat_distri_diet.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_graph_group_zone_saison.Rmd:
  path: dev/flat_graph_group_zone_saison.Rmd
  state: active
  R:
  - R/graph_group_zone_saison.R
  - R/graph_grp.R
  tests:
  - tests/testthat/test-graph_grp.R
  - tests/testthat/test-graph_group_zone_saison.R
  vignettes: []
  inflate:
    flat_file: dev/flat_graph_group_zone_saison.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_graph_normalised_group_zone_saison.Rmd:
  path: dev/flat_graph_normalised_group_zone_saison.Rmd
  state: active
  R: R/graph_normalised_group_zone_saison.R
  tests: tests/testthat/test-graph_normalised_group_zone_saison.R
  vignettes: []
  inflate:
    flat_file: dev/flat_graph_normalised_group_zone_saison.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_graph_normalised_profiles.Rmd:
  path: dev/flat_graph_normalised_profiles.Rmd
  state: active
  R: R/graph_normalised_profiles.R
  tests: tests/testthat/test-graph_normalised_profiles.R
  vignettes: []
  inflate:
    flat_file: dev/flat_graph_normalised_profiles.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_stat_occurence.Rmd:
  path: dev/flat_stat_occurence.Rmd
  state: active
  R: R/occ.R
  tests: tests/testthat/test-occ.R
  vignettes: []
  inflate:
    flat_file: dev/flat_stat_occurence.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_stat_somme_facteur.Rmd:
  path: dev/flat_stat_somme_facteur.Rmd
  state: active
  R: R/stat_somme_facteur.R
  tests: tests/testthat/test-stat_somme_facteur.R
  vignettes: []
  inflate:
    flat_file: dev/flat_stat_somme_facteur.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
flat_test_effect.Rmd:
  path: dev/flat_test_effect.Rmd
  state: active
  R: R/test_effect.R
  tests: tests/testthat/test-test_effect.R
  vignettes: []
  inflate:
    flat_file: dev/flat_test_effect.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
