---
title: "flat_diet_study.Rmd"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

#-----------------------------------------------------------------------

# abundance
    
```{r development-abundance}
# You can prepare the code of the abundance() function here
```
  
```{r function-abundance}
#' Total abundance (number of individuals) of each prey species in a stomac content dataset
#' 
#' @param data_stomac Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons).
#' @param min_abundance Minimal number of individual found in all tractus to consider the species
#' @param quantile_abundance Minimal quantil in all tractus to consider the species
#' @param proportion_abundance Minimal proportion of individual found in all tractus to consider the species
#'
#' @return dataframe Prey species, Total number of preys
#' 
#' @export
abundance = function(data_stomac, min_abundance, quantile_abundance, proportion_abundance){
  
  res_abundance = c()
  for(s in levels(data_stomac$ScientificName_accepted) ){
    tmp = data_stomac$Nbr.total.tractus[which(data_stomac$ScientificName_accepted==s)]
    res_abundance = c(res_abundance,
                      ifelse(class(tmp)=="character", yes = NA, no = sum(tmp)))
  }
  return_abundance = data.frame("species" = levels(data_stomac$ScientificName_accepted), 
                             "abundance" = res_abundance)

# Abondance > N

  par(mar=c(9,4,4,1))
  barplot(
    main = paste(
      ifelse(
        test = max(summary(data_stomac$espèce.stade)) == dim(data_stomac)[1],
        yes = paste(data_stomac$espèce.stade[1]),
        no = "Soles"
      ),
      ifelse(
        test = max(summary(data_stomac$secteur)) == dim(data_stomac)[1],
        yes = paste(data_stomac$secteur[1]),
        no = ""
      ), "abundance N>", paste(min_abundance)
    ),
    return_abundance$abundance[-which(return_abundance$abundance <= min_abundance)],
    names = return_abundance[-which(return_abundance$abundance <= min_abundance), 1],
    las = 2,
    cex.axis = 0.8
  )
  
# Abondance > quantile
  
  par(mar=c(9,4,4,1))
  barplot(
    main = paste(
      ifelse(
        test = max(summary(data_stomac$espèce.stade)) == dim(data_stomac)[1],
        yes = paste(data_stomac$espèce.stade[1]),
        no = "Soles"
      ),
      ifelse(
        test = max(summary(data_stomac$secteur)) == dim(data_stomac)[1],
        yes = paste(data_stomac$secteur[1]),
        no = ""
      ), "abundance quantile", paste(quantile_abundance)
    ),
    return_abundance[which(return_abundance$abundance > quantile(return_abundance$abundance, 
                                                                 probs = quantile_abundance, na.rm = T)), 2],
    names = return_abundance[which(return_abundance$abundance > quantile(return_abundance$abundance, 
                                                                         probs = quantile_abundance, na.rm = T)), 1],
    las = 2,
    cex.axis = 0.8
  )
  
# Abondance normalisée
  return_abundance$norm_abundance <-return_abundance$abundance/sum(return_abundance$abundance,na.rm=T)*100

  par(mar=c(9,4,4,1))
   barplot(
    main = paste(
      ifelse(
        test = max(summary(data_stomac$espèce.stade)) == dim(data_stomac)[1],
        yes = paste(data_stomac$espèce.stade[1]),
        no = "Soles"
      ),
      ifelse(
        test = max(summary(data_stomac$secteur)) == dim(data_stomac)[1],
        yes = paste(data_stomac$secteur[1]),
        no = ""
      ), "abundance proportion >", paste(proportion_abundance*100, "%")
    ),
    return_abundance$norm_abundance[-which(return_abundance$norm_abundance <= proportion_abundance)],
    names = return_abundance$species[-which(return_abundance$norm_abundance <= proportion_abundance)],
    las = 2,
    cex.axis = 0.8
  )
  
  par(mar=c(2,1,4,1))
  pie( main=paste("Abundance (>",percent_abond,"% tot preys)",
                  ifelse(test = max(summary(data_stomac$espèce.stade))==dim(data_stomac)[1], 
                         yes = paste(data_stomac$espèce.stade[1]), no = "Soles"),
       ifelse(test = max(summary(data_stomac$secteur))==dim(data_stomac)[1], yes=paste(data_stomac$secteur[1]), no="")),
       return_abundance$norm_abundance[which(return_abundance$norm_abundance > proportion_abundance)],
      labels=return_abundance[which(return_abundance$norm_abundance > proportion_abundance),1])
  
  return(return_abundance)
  #res_abundance[which(res_abundance$abundance>50),]
}
```
  
```{r example-abundance}
library(chopin.project)
abundance(data_stomac = stomac_soles, min_abundance = 5, quantile_abundance = 0.95, proportion_abundance = 0.95)
```
  
```{r tests-abundance}
test_that("abundance works", {
  expect_true(inherits(abundance, "function")) 
})
```

#-----------------------------------------------------------------------

# occurence
    
```{r development-occurence}
# You can prepare the code of the occurence() function here
```
  
```{r function-occurence}
#' Occurrence (%number over number of all preys) of each prey species in a stomac content dataset
#' 
#' @param data_stomac Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons).
#'
#' @return dataframe Prey species, Total proportion in all tractus
#' 
#' @export
occurence = function(data_stomac){
  
  res_occurence = c()
  for(s in levels(data_stomac$ScientificName_accepted) ){
    res_occurence = c(res_occurence,
                      length(data_stomac[which(data_stomac$ScientificName_accepted==s),]$N.poissons))
  }
  res_occurence = res_occurence/length(table(data_stomac$N.poissons)[which(table(data_stomac$N.poissons)!=0)])*100
  res_occurence = data.frame(levels(data_stomac$ScientificName_accepted), res_occurence)
  
  return(res_occurence)
}
```
  
```{r example-occurence}
library(chopin.project)
occurence(stomac_soles)
```
  
```{r tests-occurence}
test_that("occurence works", {
  expect_true(inherits(occurence, "function")) 
})
```
  

#-----------------------------------------------------------------------

# list_grp
    
```{r development-list_grp}
# You can prepare the code of the list_grp() function here
```
  
```{r function-list_grp}
#' Create subdatasets of stomach content data depending on sole age and sector.
#' 
#' Description
#' 
#' @param dataset Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons). Studied columns are 'espèce.stade' and 'secteur'.
#'
#' @return a list of stomach content subdatasets of interest: G0_CH, G0_EM, G0_FN, G0_FS, G1_CH, G1_EM, G1_FN, G1_FS, G2_FN, G2_EM
#' 
#' @export

list_grp = function(dataset){
  
  CH = dataset[which(dataset$secteur=="Chenal"),]
  EM = dataset[which(dataset$secteur=="Embouchure"),]
  FN = dataset[which(dataset$secteur=="Fosse Nord"),]
  FS = dataset[which(dataset$secteur=="Fosse Sud"),]

  G0 = dataset[which(dataset$espèce.stade=="Sole G0"),]
  G0_juin = dataset[which(dataset$espèce.stade=="Sole G0" & dataset$Campagne=="Print-17"),]
  G0_oct = dataset[which(dataset$espèce.stade=="Sole G0" & dataset$Campagne=="Aut-17"),]
  G0_CH = dataset[which(dataset$espèce.stade=="Sole G0" & dataset$secteur=="Chenal"),]
  G0_EM = dataset[which(dataset$espèce.stade=="Sole G0" & dataset$secteur=="Embouchure"),]
  G0_FN = dataset[which(dataset$espèce.stade=="Sole G0" & dataset$secteur=="Fosse Nord"),]
  G0_FS = dataset[which(dataset$espèce.stade=="Sole G0" & dataset$secteur=="Fosse Sud"),]

  G1 = dataset[which(dataset$espèce.stade=="Sole G1"),]
  G1_juin = dataset[which(dataset$espèce.stade=="Sole G1" & dataset$Campagne=="Print-17"),]
  G1_oct = dataset[which(dataset$espèce.stade=="Sole G1" & dataset$Campagne=="Aut-17"),]
  G1_CH = dataset[which(dataset$espèce.stade=="Sole G1" & dataset$secteur=="Chenal"),]
  G1_EM = dataset[which(dataset$espèce.stade=="Sole G1" & dataset$secteur=="Embouchure"),]
  G1_FN = dataset[which(dataset$espèce.stade=="Sole G1" & dataset$secteur=="Fosse Nord"),]
  G1_FS = dataset[which(dataset$espèce.stade=="Sole G1" & dataset$secteur=="Fosse Sud"),]

  G2 = dataset[which(dataset$espèce.stade=="Sole G2"),]
  G2_FN = dataset[which(dataset$espèce.stade=="Sole G2" & dataset$secteur=="Fosse Nord"),]
  G2_EM = dataset[which(dataset$espèce.stade=="Sole G2" & dataset$secteur=="Octeville"),]

  list("Chenal"=CH, "Embouchure"=EM, "Fosse Nord"=FN, "Fosse Sud"=FS, 
       "Sole G0"=G0, "Sole G0 printemps"=G0_juin, "Sole G0 automne"=G0_oct,
       "G0_CH"=G0_CH, "G0_EM"=G0_EM,"G0_FN"=G0_FN,"G0_FS"=G0_FS,
       "Sole G1"=G1, "Sole G1 printemps"=G1_juin, "Sole G1 automne"=G1_oct,
       "G1_CH"=G1_CH, "G1_EM"=G1_EM,"G1_FN"=G1_FN,"G1_FS"=G1_FS,
       "Sole G2"=G2, "G2_EM"=G2_EM,"G2_FN"=G2_FN)
}
```
  
```{r example-list_grp}
library(chopin.project)
list_grps = list_grp(stomac_soles)
```
  
```{r tests-list_grp}
test_that("list_grp works", {
  expect_true(inherits(list_grp, "function")) 
})
```
  

#-----------------------------------------------------------------------

# distri_diet

```{r development-distri_diet}
# Prepare the code of your function here
```

```{r function-distri_diet}
#' distri_diet Title
#'
#' @param data_stomac Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons)
#'
#' @return Matrix of proportion of each prey compared to the total number of preys in each fish tag
#' @export
#'
#' @examples
distri_diet = function(data_stomac){

  # List of fish sampled tags
  fish_samp = names(which(table(data_stomac$N.poissons)!=0))
  
  # List of prey names
  preys = levels(data_stomac$ScientificName_accepted)

  # Empty matrix with preys in rows and fish tag in columns
  diets = matrix(NA, nrow = length(preys), ncol=length(fish_samp))
  rownames(diets) = preys

  # For each fish tag
  for(f in 1:length(fish_samp)){

    # Get the total sum of number prey in each fish tag tractus
    abundance_tot = sum( data_stomac[data_stomac$N.poissons==fish_samp[f],]$Nbr.total.tractus, na.rm=T)

    # Get the proportion of each given prey in the total number of preys in each fish tag tractus (Get the total number of each type of prey for each fish tag, divided by the total number of preys in the tractus of this given fish)
    for(p in data_stomac[data_stomac$N.poissons==fish_samp[f],]$ScientificName_accepted){
      diets[which(rownames(diets)==p),f] = sum(data_stomac[data_stomac$N.poissons==fish_samp[f]&
                                                             data_stomac$ScientificName_accepted==p,]$Nbr.total.tractus,na.rm=T) / abundance_tot
    }}

  as.data.frame(diets)
 colnames(diets) <- fish_samp
 
 diets
}
```

```{r examples-distri_diet}
library(chopin.project)
distri_diet(stomac_soles)
```

```{r tests-distri_diet}
test_that("distri_diet works", {
  expect_true(inherits(distri_diet, "function"))
})
```

#-----------------------------------------------------------------------

# get_res_diet
    
```{r development-get_res_diet}
# You can prepare the code of the get_res_diet() function here
```
  
```{r function-get_res_diet}
#' Pie of stomach content with proportions of each major prey
#' 
#' Description
#' 
#' @param main Legend for the group of soles studied
#' @param grp Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons)
#' @param min_occur Minimal occurence of preys in tractus considered in the plot (0-1)
#' @param min_abond Minimal abondance of preys in tractus considered in the plot (0-1)
#'
#' @return Pie graph
#' 
#' @export
get_res_diet = function(main, grp, min_occur, min_abond){

  # Get proportion of prey species in each studied fish
  res_distri_diet = distri_diet(data_stomac = grp)

  # Taux d'occurence de chaque proie: #soles dans lesquelles la proie a été retrouvée
  occ = c()
  for(l in 1:dim(res_distri_diet)[1]){
    occ=c(occ, length(na.omit(res_distri_diet[l,])))
  }
  occ = occ/dim(res_distri_diet)[2]


  # Min, médiane et max des #proie/#total tractus dans les estomacs des soles dans lequelles la proie a été retrouvée
  min_abun = med_abun = max_abun = c()
  for(l in 1:dim(res_distri_diet)[1]){
    min_abun=c(min_abun, ifelse(occ[l]==0, yes = 0, no = min(na.omit(res_distri_diet[l,]))))
    med_abun=c(med_abun, ifelse(occ[l]==0, yes = 0, no = median(na.omit(res_distri_diet[l,]))))
    max_abun=c(max_abun, ifelse(occ[l]==0, yes = 0, no = max(na.omit(res_distri_diet[l,]))))
  }

  par(mar=c(1,4,3,2))

  pie(main = paste("Normalised %abundance for ", main,
                   "\n for species with %abundance >",min_abond*100,
                   "% and %occurance >",min_occur*100,"%", sep=""),
      med_abun[-which(med_abun<min_abond|occ<min_occur)]/
        sum(med_abun[-which(med_abun<min_abond|occ<min_occur)]),
      labels = rownames(res_distri_diet)[-which(med_abun<min_abond|occ<min_occur)]
      )

  res_pie = round((med_abun[-which(med_abun<min_abond|occ<min_occur)]/
          sum(med_abun[-which(med_abun<min_abond|occ<min_occur)]))*100,digits = 3)
  res_pie = data.frame("taxon" = table_species$taxon[-which(med_abun<min_abond|occ<min_occur)],
                       "species" = rownames(res_distri_diet)[-which(med_abun<min_abond|occ<min_occur)],
                       "tx.abun" = res_pie)

  res = cbind("%occ"=round(occ*100,digits = 3),
              "min %abun"=round(min_abun*100,digits = 3),
              "med %abun"=round(med_abun*100,digits = 3),
              "max %abun"=round(max_abun*100,digits = 3))

  rownames(res) = rownames(res_distri_diet)

  res_pie$species = as.factor(res_pie$species)
  res_pie$species = factor(
    res_pie$species,
    levels = levels(res_pie$species)[order(res_pie$taxon)],
    labels = levels(res_pie$species)[order(res_pie$taxon)]
  )

  list("res"=res,
       "med %abun"=data.frame(res_pie))
}
```
  
```{r example-get_res_diet}
library(chopin.project)
res_all_soles = get_res_diet(main = "ALL SOLES", grp=stomac_soles, min_abond =0.1, min_occur = 0.1)
```
  
```{r tests-get_res_diet}
test_that("get_res_diet works", {
  expect_true(inherits(get_res_diet, "function")) 
})
```

#-----------------------------------------------------------------------

# piechart_diet
    
```{r development-piechart_diet}
library(tidyverse)
library(scales)
```
  
```{r function-piechart_diet}
#' Piechart of diet for a group of soles
#' 
#' with type of color by taxon
#' 
#' @return
#' 
#' @export
piechart_diet = function(res_pie){

  res_pie$col=rep.int(NA,times = length(res_pie$species))
  for(i in 1:dim(res_pie)[1]){
    res_pie$col[i] = list_taxon$col_species[which(list_taxon$species==as.character(res_pie$species[i]))]
  }
  
  # intersect(as.character(res_pie$species), list_taxon$species)

  res_pie <- res_pie %>%
    arrange(desc(species)) %>%
    mutate(prop = tx.abun / sum(res_pie$tx.abun) *100) %>%
    mutate(ypos = cumsum(prop)- 0.5*prop )

  bp<- ggplot(res_pie, aes(x="", y=tx.abun, fill=species))+
    geom_bar(width = 1, stat = "identity", color="white")
  pie <- bp + coord_polar("y", start=0)
  blank_theme <- theme_minimal()+
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.border = element_blank(),
      panel.grid=element_blank(),
      axis.ticks = element_blank(),
      plot.title=element_text(size=12, face="bold")
    )
  pie +  
    scale_fill_manual(values=res_pie$col[order(res_pie$species)]) +
    blank_theme+theme(axis.text.x=element_blank()) +
    labs(fill="Espèces") +
    geom_text(aes(y = ypos,
                  label = percent(res_pie$tx.abun/100, accuracy = 1)),
                  size=4)

}
```
  
```{r example-piechart_diet}
library(chopin.project)
library(tidyverse)
library(scales)

res_G0_emb_juin = get_res_diet(
  main = "G0 Embouchure printemps",
  grp = stomac_soles[which(
    stomac_soles$secteur == "Embouchure" &
      stomac_soles$espèce.stade == "Sole G0" &
      stomac_soles$Campagne == "Print-17"
  ), ],
  min_abond = 0.1,  min_occur = 0.1
)
piechart_diet(res_pie = res_G0_emb_juin$`med %abun`)
```
  
```{r tests-piechart_diet}
test_that("piechart_diet works", {
  expect_true(inherits(piechart_diet, "function")) 
})
```


#-----------------------------------------------------------------------

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_diet_study.Rmd", vignette_name = NA)
```
