---
title: "flat_graph_group_zone_saison.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# graph_grp
    
```{r development-graph_grp}
# You can prepare the code of the graph_grp() function here
```
  
```{r function-graph_grp}
#' Dotplot 
#' 
#' Description
#' 
#' @param data 
#' @param variable 
#' @param label_y 
#' @param group 
#' @param title 
#' @param label_data 
#' @param wd 
#'
#' @return
#' 
#' @export
graph_grp <- function(data, grp, variable, label_data, label_y, title){
  
   ggplot(data, aes(x=.data[[grp]], y=.data[[variable]], color=.data[[grp]], fill=.data[[grp]])) + 
    geom_dotplot(binaxis='y', stackdir='center')+
    theme_bw() +
    theme(legend.position="none") +
    #theme(axis.text.x=element_text(size=9, angle=45, hjust=1), legend.position="bottom") +
    stat_summary(fun = mean, geom="crossbar", size=0.5, color="darkgrey", width=.5) +
    stat_summary(fun = median, geom="crossbar", size=0.5, color="black", width=.5) +
    #guides(col=guide_legend(nrow=2)) +
    labs(title=title, x=NULL, y=NULL)

}
```
  
```{r example-graph_grp}
sub_benthos_contam <- benthos_contam |> 
  select(grp, season, zone, starts_with("somme")  )
sub_benthos_contam <- as.data.frame(sub_benthos_contam)

graph_grp(
  data = sub_benthos_contam,
  grp = "grp",
  variable = "sommePCB_ng_gdw",
  label_data = "soles et benthos",
  label_y = expression(paste(sum(), "PCB")),
  title = "GROUPE"
)
```
  
```{r tests-graph_grp}
test_that("graph_grp works", {
  expect_true(inherits(graph_grp, "function")) 
})
```
  

# graph_group_zone_saison

```{r development-graph_group_zone_saison}
# Prepare the code of your function here
library(ggplot2)
library(cowplot)
```

```{r function-graph_group_zone_saison}
#' graph_group_zone_saison  FONCTION GRAPHIQUE TAXON, ZONE, SAISON
#'
#' @param data 
#' @param label_data 
#' @param variable 
#' @param label_y 
#' @param wd 
#'
#' @return 1
#' @export
#'
#' @examples
GRAPH_group_zone_saison = function(data,label_data, variable,label_y, wd){
  
  p1 = graph_grp(
    data = data,
    grp = "grp",
    variable = variable,
    label_data = label_data,
    label_y = label_y,
    title = "GROUPE"
  )
  
  p2 = graph_grp(
    data = data,
    grp = "zone",
    variable = variable,
    label_data = label_data,
    label_y = label_y,
    title = "ZONE"
  )
  
  p3 = graph_grp(
    data = data,
    grp = "season",
    variable = variable,
    label_data = label_data,
    label_y = label_y,
    title = "SAISON"
  )

  plot=ggdraw()+
    draw_plot(p1, x=0, y=0, width=0.35, height=1) +
    draw_plot(p2, x=0.35,y=0, 0.45, 1) +
    draw_plot(p3, x=0.8,y=0, 0.2, 1)
  
  ggsave(
    filename = paste(wd, label_data, "_", variable, "_group_zone_saison.jpeg", sep = ""),
    plot = plot,
    device = "jpeg",
    width = 20,
    height = 5,
    units = "cm",
    dpi = 300
  )
}
```

```{r examples-graph_group_zone_saison}
sub_benthos_contam <- benthos_contam |> 
  select(grp, season, zone, starts_with("somme")  )
sub_benthos_contam <- as.data.frame(sub_benthos_contam)

GRAPH_group_zone_saison(data = sub_benthos_contam, label_data = "benthos", variable = "sommePCB_ng_gdw", label_y=expression(paste(sum(),"PCB")), wd = "")
```

```{r tests-graph_group_zone_saison}
test_that("graph_group_zone_saison works", {
  expect_true(inherits(graph_group_zone_saison, "function"))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_graph_group_zone_saison.Rmd", vignette_name = NA)
```

