# WARNING - Generated by {fusen} from dev/flat_graph_normalised_profiles.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("graph_normalised_profiles works", {
  expect_true(inherits(graph_normalised_profiles, "function"))
})
