# WARNING - Generated by {fusen} from dev/flat_diet_study.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_res_diet works", {
  expect_true(inherits(get_res_diet, "function")) 
})
