# WARNING - Generated by {fusen} from dev/flat_graph_group_zone_saison.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("graph_grp works", {
  expect_true(inherits(graph_grp, "function")) 
})
