# WARNING - Generated by {fusen} from dev/flat_stat_occurence.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("occ works", {
 vec <- c(0, 1, 5, 2, 12, NA)
testthat::expect_equal( occ(vector = vec), 0.8)
})
