# WARNING - Generated by {fusen} from dev/flat_test_effect.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("test_effect works", {
  expect_true(inherits(test_effect, "function"))
})
