---
title: "CHOPIN_Stomac_content"
output: word_document
    # fig_width: 10
    # fig_height: 7
    # fig_caption: true
---


```{r , echo=FALSE, message=FALSE, warning=FALSE}
##### [CHOPIN] STOMACH CONTENTS B. Chouquet

# clear workspace
rm(list=ls())

# save working directory
wd <- getwd()


#load datasets

setwd("C:/Users/florence.mounier/Work Folders/Documents/Mes documents/CDD IR CHOPIN/DATA/DATASETS")

library(readxl)

stomacG0G1 <- as.data.frame(read_excel("BDD_contenus_stomacaux_CHOPIN_avril_2020.xlsx"))
stomacG2 <- read_excel("BDD_contenus_stomacaux_CHOPIN_soles_G2_octeville.xlsx")


stomac_soles = rbind(stomacG0G1[which(stomacG0G1$`espèce/stade`=="Sole G0"|stomacG0G1$`espèce/stade`=="Sole G1"),],
                     stomacG2)

# remove parasites & detritus & empty
stomac_soles = stomac_soles[-which(stomac_soles$Statut=="déchet"|
                                     stomac_soles$Statut=="Déchet"|
                                     stomac_soles$Statut=="Parasite"|
                                     stomac_soles$Statut=="RAS"|
                                     stomac_soles$ScientificName_accepted=="Divers"|
                                     stomac_soles$ScientificName_accepted=="Divers_débris"|
                                     stomac_soles$ScientificName_accepted=="Non identifié"|
                                     stomac_soles$ScientificName_accepted=="Ponte_nd"|
                                     stomac_soles$ScientificName_accepted=="Animalia 4"|
                                     stomac_soles$ScientificName_accepted=="Animalia 5"|
                                     stomac_soles$ScientificName_accepted=="Pleuronectes platessa_écailles"|
                                     stomac_soles$ScientificName_accepted=="Actinopterygii_écaille"),]
summary(as.factor(stomac_soles$Statut))

stomac_soles$`Nbr total tractus` = as.numeric(stomac_soles$`Nbr total tractus`)

stomac_soles$ScientificName_accepted = as.factor(stomac_soles$ScientificName_accepted)
levels(stomac_soles$ScientificName_accepted)

stomac_soles$`espèce/stade` = as.factor(stomac_soles$`espèce/stade`)
levels(stomac_soles$`espèce/stade`)

# Number of fish
stomac_soles$`N°poissons` = as.factor(stomac_soles$`N°poissons`)
length(levels(stomac_soles$`N°poissons`))

# Sectors
stomac_soles$secteur = as.factor(stomac_soles$secteur)
levels(stomac_soles$secteur)

stomac_soles = data.frame(stomac_soles)

list_grp = function(dataset){
  G0_CH = dataset[which(dataset$espèce.stade=="Sole G0"& dataset$secteur=="Chenal"),]
  G0_EM = dataset[which(dataset$espèce.stade=="Sole G0"& dataset$secteur=="Embouchure"),]
  G0_FN = dataset[which(dataset$espèce.stade=="Sole G0"& dataset$secteur=="Fosse Nord"),]
  G0_FS = dataset[which(dataset$espèce.stade=="Sole G0"& dataset$secteur=="Fosse Sud"),]
  
  G1_CH = dataset[which(dataset$espèce.stade=="Sole G1"& dataset$secteur=="Chenal"),]
  G1_EM = dataset[which(dataset$espèce.stade=="Sole G1"& dataset$secteur=="Embouchure"),]
  G1_FN = dataset[which(dataset$espèce.stade=="Sole G1"& dataset$secteur=="Fosse Nord"),]
  G1_FS = dataset[which(dataset$espèce.stade=="Sole G1"& dataset$secteur=="Fosse Sud"),]
  
  G2_FN = dataset[which(dataset$espèce.stade=="Sole G2"& dataset$secteur=="Fosse Nord"),]
  G2_EM = dataset[which(dataset$espèce.stade=="Sole G2"& dataset$secteur=="Octeville"),]
  
  list("G0_CH"=G0_CH, "G0_EM"=G0_EM,"G0_FN"=G0_FN,"G0_FS"=G0_FS,
                   "G1_CH"=G1_CH, "G1_EM"=G1_EM,"G1_FN"=G1_FN,"G1_FS"=G1_FS,
                   "G2_EM"=G2_EM,"G2_FN"=G2_FN) 
}

#####################################################################################################


# Function abundances of each prey
abundance = function(data_stomac){
  
  res_abundance = c()
  for(s in levels(data_stomac$ScientificName_accepted) ){
    tmp = data_stomac$Nbr.total.tractus[which(data_stomac$ScientificName_accepted==s)]
    res_abundance = c(res_abundance,
                      ifelse(class(tmp)=="character", yes = NA, no = sum(tmp)))
  }
  res_abundance = data.frame(levels(data_stomac$ScientificName_accepted), res_abundance)
  #res_abundance[which(res_abundance$res_abundance>50),]

}


# Number of occurences of each preys in stomacs
ordered_alphab_preys = table(stomac_soles$ScientificName_accepted)
ordered_occur_preys = summary(stomac_soles$ScientificName_accepted)

occurence = function(data_stomac){
  
  res_occurence = c()
  for(s in levels(data_stomac$ScientificName_accepted) ){
    res_occurence = c(res_occurence,
                      length(data_stomac[which(data_stomac$ScientificName_accepted==s),]$N.poissons))
  }
  res_occurence = res_occurence/length(table(data_stomac$N.poissons)[which(table(data_stomac$N.poissons)!=0)])*100
  res_occurence = data.frame(levels(data_stomac$ScientificName_accepted), res_occurence)
}

distri_diet = function(data_stomac){
  
  fish_samp = names(which(table(data_stomac$N.poissons)!=0))
  preys = levels(data_stomac$ScientificName_accepted)
  
  diets = matrix(NA, nrow = length(preys), ncol=length(fish_samp))
  rownames(diets) = preys
  
  for(f in 1:length(fish_samp)){
    
    abundance_tot = sum( data_stomac[data_stomac$N.poissons==fish_samp[f],]$Nbr.total.tractus, na.rm=T)
    
    for(p in data_stomac[data_stomac$N.poissons==fish_samp[f],]$ScientificName_accepted){
      diets[which(rownames(diets)==p),f] = sum(data_stomac[data_stomac$N.poissons==fish_samp[f]&
                                 data_stomac$ScientificName_accepted==p,]$Nbr.total.tractus,na.rm=T) / abundance_tot
    }}
      
    diets              
                 
  }
  
  

#----------------

get_res = function(grp, percent_occur, percent_abond){
  
  # abundance
  res_grp = abundance(data_stomac = grp)
  
  par(mfrow=c(1,1))
  par(mar=c(9,4,4,1))
  barplot(main=paste(ifelse(test = max(summary(grp$espèce.stade))==dim(grp)[1], yes = paste(grp$espèce.stade[1]), no = "Soles"),
                     ifelse(test = max(summary(grp$secteur))==dim(grp)[1], yes=paste(grp$secteur[1]), no="")), 
          res_grp$res_abundance[-which(res_grp$res_abundance<=1)],
          names=res_grp[-which(res_grp$res_abundance<=1),1], las=2, cex.axis=0.8)
  barplot(main=paste(ifelse(test = max(summary(grp$espèce.stade))==dim(grp)[1], yes = paste(grp$espèce.stade[1]), no = "Soles"),
                     ifelse(test = max(summary(grp$secteur))==dim(grp)[1], yes=paste(grp$secteur[1]), no=""), ">95%"),
          res_grp[which(res_grp$res_abundance>quantile(res_grp$res_abundance, probs = 0.95, na.rm=T)),2],
          names=res_grp[which(res_grp$res_abundance>quantile(res_grp$res_abundance, probs = 0.95, na.rm=T)),1],
          las=2, cex.axis=0.8)
  
  norm_abundance=res_grp$res_abundance/sum(res_grp$res_abundance,na.rm=T)*100
  
  par(mar=c(2,1,4,1))
  pie( main=paste("Abundance (>",percent_abond,"% tot preys)",
                  ifelse(test = max(summary(grp$espèce.stade))==dim(grp)[1], 
                         yes = paste(grp$espèce.stade[1]), no = "Soles"),
       ifelse(test = max(summary(grp$secteur))==dim(grp)[1], yes=paste(grp$secteur[1]), no="")),
       norm_abundance[which(norm_abundance > percent_abond)],
      labels=res_grp[which(norm_abundance > percent_abond),1])
  
  # occurence
  par(mar=c(2,1,4,1))
  pie_chart = occurence(grp)
  pie(pie_chart[which(pie_chart$res_occurence > percent_occur),2],
      labels = pie_chart[which(pie_chart$res_occurence > percent_occur),1],
      main=paste("Occurence (>",percent_occur,"% stomacs)",
                 ifelse(test = max(summary(grp$espèce.stade))==dim(grp)[1], yes = paste(grp$espèce.stade[1]), no = "Soles"),
                 ifelse(test = max(summary(grp$secteur))==dim(grp)[1], yes=paste(grp$secteur[1]), no="")))

  
   # distribution bol alimentaire
  res_distri_diet = distri_diet(data_stomac = stomac_soles)
  
  occ = c()
  for(l in 1:dim(res_distri_diet)[1]){
    occ=c(occ, length(na.omit(res_distri_diet[l,])))
  }
  abun = c()
  for(l in 1:dim(res_distri_diet)[1]){
    abun=c(abun, max(na.omit(res_distri_diet[l,])))
  }
  res_distri_diet_red = res_distri_diet[which(occ>10),]
  res_distri_diet_red = res_distri_diet[which(abun>0.2),]
  res_distri_diet_red = res_distri_diet[intersect(which(abun>0.2),which(occ>10)),]
  
  par(mfrow=c(2,2))
  par(mar=c(3,4,2,2))
  
  for(p in 1:dim(res_distri_diet_red)[1]){
    plot(density(na.omit(res_distri_diet_red[p,])), type="l",
         main=paste(rownames(res_distri_diet_red)[p]), ylim=c(0,18), xlim=c(0,1))
  }
  
  }

list_grps = list_grp(stomac_soles)

```

# Tous les poissons
```{r , echo=FALSE}
get_res(grp=stomac_soles, percent_abond =5, percent_occur = 15)
```

# Par classe d'âge 
```{r , echo=FALSE}
get_res(stomac_soles[which(stomac_soles$espèce.stade=="Sole G0"),], percent_abond =5, percent_occur = 15)
get_res(stomac_soles[which(stomac_soles$espèce.stade=="Sole G1"),], percent_abond =5, percent_occur = 15)
get_res(stomac_soles[which(stomac_soles$espèce.stade=="Sole G2"),], percent_abond =5, percent_occur = 15)

```

# Par zone 
```{r , echo=FALSE}
get_res(stomac_soles[which(stomac_soles$secteur=="Chenal"),], percent_abond =5, percent_occur = 15)
get_res(stomac_soles[which(stomac_soles$secteur=="Embouchure"),], percent_abond =5, percent_occur = 15)
get_res(stomac_soles[which(stomac_soles$secteur=="Octeville"),], percent_abond =5, percent_occur = 15)
get_res(stomac_soles[which(stomac_soles$secteur=="Fosse Sud"),], percent_abond =5, percent_occur = 15)
get_res(stomac_soles[which(stomac_soles$secteur=="Fosse Nord"),], percent_abond =5, percent_occur = 15)
```


# Par zone et classe d'âge

```{r , echo=FALSE}
sapply(list_grps, FUN = get_res, percent_abond =5, percent_occur = 15)

```