---
title: "Representation graphique des sommes par famille par zone et saison"
author: "Florence Mounier"
date: "2025-01-24"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(chopin.project)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(cowplot)
```

## SEDIMENTS

```{r}
GRAPH_group_zone_saison(data = sed_contam, label_data = "SEDIMENTS", variable = "sommePCB_ng_gdw", label_y=expression(paste(sum(),"PCB")), wd="")
GRAPH_group_zone_saison(data = sed_contam,label_data = "SEDIMENTS",  variable = "sommePFCA_ng_gdw", label_y=expression(paste(sum(),"PFCA")), wd="Output/SEDIMENTS/")
GRAPH_group_zone_saison(data = sed_contam,label_data = "SEDIMENTS",  variable = "sommePFSA_ng_gdw", label_y=expression(paste(sum(),"PFSA")), wd="Output/SEDIMENTS/")
GRAPH_group_zone_saison(data = sed_contam,label_data = "SEDIMENTS",  variable = "sommeFOSA_ng_gdw", label_y=expression(paste(sum(),"FOSA et FOSAA")), wd="Output/SEDIMENTS/")
GRAPH_group_zone_saison(data = sed_contam, label_data = "SEDIMENTS", variable = "sommeHBCDD_ng_gdw", label_y=expression(paste(sum(),"HBCDD")), wd="Output/SEDIMENTS/")
```


## BENTHOS


# Representation graphique des sommes par famille par taxon, zone et saison

```{r}
GRAPH_group_zone_saison(data = benthos_contam, label_data = "BENTHOS", variable = "sommePCB_ng_gdw", label_y=expression(paste(sum(),"PCB")), wd="")
GRAPH_group_zone_saison(data = benthos_contam,label_data = "BENTHOS",  variable = "sommePFCA_ng_gdw", label_y=expression(paste(sum(),"PFCA")), wd="")
GRAPH_group_zone_saison(data = benthos_contam,label_data = "BENTHOS",  variable = "sommePFSA_ng_gdw", label_y=expression(paste(sum(),"PFSA")), wd="")
GRAPH_group_zone_saison(data = benthos_contam,label_data = "BENTHOS",  variable = "sommeFOSA_ng_gdw", label_y=expression(paste(sum(),"FOSA et FOSAA")), wd="")
GRAPH_group_zone_saison(data = benthos_contam, label_data = "BENTHOS", variable = "sommeHBCDD_ng_gdw", label_y=expression(paste(sum(),"HBCDD")), wd="")
```


## SOLES


# Representation graphique des sommes par famille par classe d'âge, zone et saison

```{r}
GRAPH_group_zone_saison(data = soles_contam, label_data = "soles", variable = "sommePCB_ng_gdw", label_y=expression(paste(sum(),"PCB")), wd = "")
GRAPH_group_zone_saison(data = soles_contam,label_data = "soles",  variable = "sommePFCA_ng_gdw", label_y=expression(paste(sum(),"PFCA")), wd = "")
GRAPH_group_zone_saison(data = soles_contam,label_data = "soles",  variable = "sommePFSA_ng_gdw", label_y=expression(paste(sum(),"PFSA")), wd = "")
GRAPH_group_zone_saison(data = soles_contam,label_data = "soles",  variable = "sommeFOSA_ng_gdw", label_y=expression(paste(sum(),"FOSA et FOSAA")), wd = "")
GRAPH_group_zone_saison(data = soles_contam,label_data = "soles",  variable = "sommeautres_ng_gdw", label_y=expression(paste(sum(),"autres PFAS")), wd = "")
GRAPH_group_zone_saison(data = soles_contam, label_data = "soles", variable = "sommeHBCDD_ng_gdw", label_y=expression(paste(sum(),"HBCDD")), wd = "")
```

## BENTHOS ET SOLES

```{r}
sub_benthos_contam <- benthos_contam |> 
  select(grp, season, zone, starts_with("somme")  )

sub_soles_contam <- soles_contam |> 
  select(grp, season, zone, starts_with("somme")) |> 
  filter(grp == "G0")

soles_and_benthos_contam <- bind_rows(sub_benthos_contam, sub_soles_contam)
soles_and_benthos_contam$grp <- factor(soles_and_benthos_contam$grp, levels = c("Bivalves", "Crustaces","Polychetes", "G0"))
```

```{r}
p1 = graph_grp(data = soles_and_benthos_contam, grp = "grp", variable = "sommePCB_ng_gdw", label_data = "soles et benthos", label_y=expression(paste(sum(),"PCB")), title = expression(paste(sum(),"PCB")))
p2 = graph_grp(data = soles_and_benthos_contam, grp = "grp", variable = "sommePFAS_ng_gdw", label_data = "soles et benthos", label_y=expression(paste(sum(),"PFAS")), title = expression(paste(sum(),"PFAS")))
p3 = graph_grp(data = soles_and_benthos_contam, grp = "grp", variable = "sommeHBCDD_ng_gdw", label_data = "soles et benthos", label_y=expression(paste(sum(),"HBCDD")), title = expression(paste(sum(),"HBCDD")))

plot <- plot_grid(p1, p2, p3, ncol = 3)

  ggsave(
    filename = "contamination_somme_famille_publi.jpeg",
    plot = plot,
    device = "jpeg",
    width = 25,
    height = 10,
    units = "cm",
    dpi = 300
  )
```

```{r}
p1 = graph_grp(data = soles_and_benthos_contam, grp = "grp", variable = "sommePFCA_ng_gdw", label_data = "soles et benthos", label_y=expression(paste(sum(),"PFCA")), title = expression(paste(sum(),"PFCA")))
p2 = graph_grp(data = soles_and_benthos_contam, grp = "grp", variable = "sommePFSA_ng_gdw", label_data = "soles et benthos", label_y=expression(paste(sum(),"PFSA")), title = expression(paste(sum(),"PFSA")))
p3 = graph_grp(data = soles_and_benthos_contam, grp = "grp", variable = "sommeFOSA_ng_gdw", label_data = "soles et benthos", label_y=expression(paste(sum(),"FOSA et FOSAA")), title = expression(paste(sum(),"FOSA et FOSAA")))


plot <- plot_grid(p1, p2, p3, ncol = 3)

  ggsave(
    filename = "contamination_somme_PFASsousfamille_publi.jpeg",
    plot = plot,
    device = "jpeg",
    width = 25,
    height = 10,
    units = "cm",
    dpi = 300
  )
```

