# WARNING - Generated by {fusen} from dev/flat_diet_study.Rmd: do not edit by hand # nolint: line_length_linter.

#' Total abundance (number of individuals) of each prey species in a stomac content dataset
#' 
#' @param data_stomac Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons).
#' @param min_abundance Minimal number of individual found in all tractus to consider the species
#' @param quantile_abundance Minimal quantil in all tractus to consider the species
#' @param proportion_abundance Minimal proportion of individual found in all tractus to consider the species
#'
#' @return dataframe Prey species, Total number of preys
#' 
#' @export
#' @examples
#' library(chopin.project)
#' abundance(data_stomac = stomac_soles, min_abundance = 5, quantile_abundance = 0.95, proportion_abundance = 0.95)
abundance = function(data_stomac, min_abundance, quantile_abundance, proportion_abundance){
  
  res_abundance = c()
  for(s in levels(data_stomac$ScientificName_accepted) ){
    tmp = data_stomac$Nbr.total.tractus[which(data_stomac$ScientificName_accepted==s)]
    res_abundance = c(res_abundance,
                      ifelse(class(tmp)=="character", yes = NA, no = sum(tmp)))
  }
  return_abundance = data.frame("species" = levels(data_stomac$ScientificName_accepted), 
                             "abundance" = res_abundance)

# Abondance > N

  par(mar=c(9,4,4,1))
  barplot(
    main = paste(
      ifelse(
        test = max(summary(data_stomac$espèce.stade)) == dim(data_stomac)[1],
        yes = paste(data_stomac$espèce.stade[1]),
        no = "Soles"
      ),
      ifelse(
        test = max(summary(data_stomac$secteur)) == dim(data_stomac)[1],
        yes = paste(data_stomac$secteur[1]),
        no = ""
      ), "abundance N>", paste(min_abundance)
    ),
    return_abundance$abundance[-which(return_abundance$abundance <= min_abundance)],
    names = return_abundance[-which(return_abundance$abundance <= min_abundance), 1],
    las = 2,
    cex.axis = 0.8
  )
  
# Abondance > quantile
  
  par(mar=c(9,4,4,1))
  barplot(
    main = paste(
      ifelse(
        test = max(summary(data_stomac$espèce.stade)) == dim(data_stomac)[1],
        yes = paste(data_stomac$espèce.stade[1]),
        no = "Soles"
      ),
      ifelse(
        test = max(summary(data_stomac$secteur)) == dim(data_stomac)[1],
        yes = paste(data_stomac$secteur[1]),
        no = ""
      ), "abundance quantile", paste(quantile_abundance)
    ),
    return_abundance[which(return_abundance$abundance > quantile(return_abundance$abundance, 
                                                                 probs = quantile_abundance, na.rm = T)), 2],
    names = return_abundance[which(return_abundance$abundance > quantile(return_abundance$abundance, 
                                                                         probs = quantile_abundance, na.rm = T)), 1],
    las = 2,
    cex.axis = 0.8
  )
  
# Abondance normalisée
  return_abundance$norm_abundance <-return_abundance$abundance/sum(return_abundance$abundance,na.rm=T)*100

  par(mar=c(9,4,4,1))
   barplot(
    main = paste(
      ifelse(
        test = max(summary(data_stomac$espèce.stade)) == dim(data_stomac)[1],
        yes = paste(data_stomac$espèce.stade[1]),
        no = "Soles"
      ),
      ifelse(
        test = max(summary(data_stomac$secteur)) == dim(data_stomac)[1],
        yes = paste(data_stomac$secteur[1]),
        no = ""
      ), "abundance proportion >", paste(proportion_abundance*100, "%")
    ),
    return_abundance$norm_abundance[-which(return_abundance$norm_abundance <= proportion_abundance)],
    names = return_abundance$species[-which(return_abundance$norm_abundance <= proportion_abundance)],
    las = 2,
    cex.axis = 0.8
  )
  
  par(mar=c(2,1,4,1))
  pie( main=paste("Abundance (>",percent_abond,"% tot preys)",
                  ifelse(test = max(summary(data_stomac$espèce.stade))==dim(data_stomac)[1], 
                         yes = paste(data_stomac$espèce.stade[1]), no = "Soles"),
       ifelse(test = max(summary(data_stomac$secteur))==dim(data_stomac)[1], yes=paste(data_stomac$secteur[1]), no="")),
       return_abundance$norm_abundance[which(return_abundance$norm_abundance > proportion_abundance)],
      labels=return_abundance[which(return_abundance$norm_abundance > proportion_abundance),1])
  
  return(return_abundance)
  #res_abundance[which(res_abundance$abundance>50),]
}
