# WARNING - Generated by {fusen} from dev/flat_diet_study.Rmd: do not edit by hand # nolint: line_length_linter.

#' distri_diet Title
#'
#' @param data_stomac Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons)
#'
#' @return Matrix of proportion of each prey compared to the total number of preys in each fish tag
#' @export
#'
#' @examples
#' library(chopin.project)
#' distri_diet(stomac_soles)
distri_diet = function(data_stomac){

  # List of fish sampled tags
  fish_samp = names(which(table(data_stomac$N.poissons)!=0))
  
  # List of prey names
  preys = levels(data_stomac$ScientificName_accepted)

  # Empty matrix with preys in rows and fish tag in columns
  diets = matrix(NA, nrow = length(preys), ncol=length(fish_samp))
  rownames(diets) = preys

  # For each fish tag
  for(f in 1:length(fish_samp)){

    # Get the total sum of number prey in each fish tag tractus
    abundance_tot = sum( data_stomac[data_stomac$N.poissons==fish_samp[f],]$Nbr.total.tractus, na.rm=T)

    # Get the proportion of each given prey in the total number of preys in each fish tag tractus (Get the total number of each type of prey for each fish tag, divided by the total number of preys in the tractus of this given fish)
    for(p in data_stomac[data_stomac$N.poissons==fish_samp[f],]$ScientificName_accepted){
      diets[which(rownames(diets)==p),f] = sum(data_stomac[data_stomac$N.poissons==fish_samp[f]&
                                                             data_stomac$ScientificName_accepted==p,]$Nbr.total.tractus,na.rm=T) / abundance_tot
    }}

  as.data.frame(diets)
 colnames(diets) <- fish_samp
 
 diets
}
