# WARNING - Generated by {fusen} from dev/flat_diet_study.Rmd: do not edit by hand # nolint: line_length_linter.

#' Pie of stomach content with proportions of each major prey
#'
#' Description
#'
#' @param main Legend for the group of soles studied
#' @param grp Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons)
#' @param min_occur Minimal occurence of preys in tractus considered in the plot (0-1)
#' @param min_abond Minimal abondance of preys in tractus considered in the plot (0-1)
#'
#' @return Pie graph
#'
#' @export
#' @examples
#' library(chopin.project)
#' res_all_soles = get_res_diet(main = "ALL SOLES", grp=stomac_soles, min_abond =0.1, min_occur = 0.1)
get_res_diet = function(main, grp, min_occur, min_abond){

  # Get proportion of prey species in each studied fish
  res_distri_diet = distri_diet(data_stomac = grp)

  # Taux d'occurence de chaque proie: #soles dans lesquelles la proie a été retrouvée
  occ = c()
  for(l in 1:dim(res_distri_diet)[1]){
    occ=c(occ, length(na.omit(res_distri_diet[l,])))
  }
  occ = occ/dim(res_distri_diet)[2]

  # Min, médiane et max des #proie/#total tractus dans les estomacs des soles dans lequelles la proie a été retrouvée
  min_abun = med_abun = max_abun = c()
  for(l in 1:dim(res_distri_diet)[1]){
    min_abun=c(min_abun, ifelse(occ[l]==0, yes = 0, no = min(na.omit(res_distri_diet[l,]))))
    med_abun=c(med_abun, ifelse(occ[l]==0, yes = 0, no = median(na.omit(res_distri_diet[l,]))))
    max_abun=c(max_abun, ifelse(occ[l]==0, yes = 0, no = max(na.omit(res_distri_diet[l,]))))
  }

  par(mar=c(1,4,3,2))

  pie(main = paste("Normalised %abundance for ", main,
                   "\n for species with %abundance >",min_abond*100,
                   "% and %occurance >",min_occur*100,"%", sep=""),
      med_abun[-which(med_abun<min_abond|occ<min_occur)]/
        sum(med_abun[-which(med_abun<min_abond|occ<min_occur)]),
      labels = rownames(res_distri_diet)[-which(med_abun<min_abond|occ<min_occur)]
      )

  res_pie = round((med_abun[-which(med_abun<min_abond|occ<min_occur)]/
          sum(med_abun[-which(med_abun<min_abond|occ<min_occur)]))*100,digits = 3)
  res_pie = data.frame("taxon" = table_species$taxon[-which(med_abun<min_abond|occ<min_occur)],
                       "species" = rownames(res_distri_diet)[-which(med_abun<min_abond|occ<min_occur)],
                       "tx.abun" = res_pie)

  res = cbind("%occ"=round(occ*100,digits = 3),
              "min %abun"=round(min_abun*100,digits = 3),
              "med %abun"=round(med_abun*100,digits = 3),
              "max %abun"=round(max_abun*100,digits = 3))

  rownames(res) = rownames(res_distri_diet)

  res_pie$species = as.factor(res_pie$species)
  res_pie$species = factor(
    res_pie$species,
    levels = levels(res_pie$species)[order(res_pie$taxon)],
    labels = levels(res_pie$species)[order(res_pie$taxon)]
  )
  list("res"=res,
       "med %abun"=data.frame(res_pie))
}
