# WARNING - Generated by {fusen} from dev/flat_graph_group_zone_saison.Rmd: do not edit by hand # nolint: line_length_linter.

#' Dotplot 
#' 
#' Description
#' 
#' @param data 
#' @param variable 
#' @param label_y 
#' @param group 
#' @param title 
#' @param label_data 
#' @param wd 
#'
#' @return
#' 
#' @export
#' @examples
#' sub_benthos_contam <- benthos_contam |> 
#'   select(grp, season, zone, starts_with("somme")  )
#' sub_benthos_contam <- as.data.frame(sub_benthos_contam)
#'
#' graph_grp(
#'   data = sub_benthos_contam,
#'   grp = "grp",
#'   variable = "sommePCB_ng_gdw",
#'   label_data = "soles et benthos",
#'   label_y = expression(paste(sum(), "PCB")),
#'   title = "GROUPE"
#' )
graph_grp <- function(data, grp, variable, label_data, label_y, title){
  
   ggplot(data, aes(x=.data[[grp]], y=.data[[variable]], color=.data[[grp]], fill=.data[[grp]])) + 
    geom_dotplot(binaxis='y', stackdir='center')+
    theme_bw() +
    theme(legend.position="none") +
    #theme(axis.text.x=element_text(size=9, angle=45, hjust=1), legend.position="bottom") +
    stat_summary(fun = mean, geom="crossbar", size=0.5, color="darkgrey", width=.5) +
    stat_summary(fun = median, geom="crossbar", size=0.5, color="black", width=.5) +
    #guides(col=guide_legend(nrow=2)) +
    labs(title=title, x=NULL, y=NULL)

}
