# WARNING - Generated by {fusen} from dev/flat_graph_group_zone_saison.Rmd: do not edit by hand # nolint: line_length_linter.

#' graph_group_zone_saison  FONCTION GRAPHIQUE TAXON, ZONE, SAISON
#'
#' @param data 
#' @param label_data 
#' @param variable 
#' @param label_y 
#' @param wd 
#'
#' @return 1
#' @export
#'
#' @examples
#' sub_benthos_contam <- benthos_contam |> 
#'   select(grp, season, zone, starts_with("somme")  )
#' sub_benthos_contam <- as.data.frame(sub_benthos_contam)
#'
#' GRAPH_group_zone_saison(data = sub_benthos_contam, label_data = "benthos", variable = "sommePCB_ng_gdw", label_y=expression(paste(sum(),"PCB")), wd = "")
GRAPH_group_zone_saison = function(data,label_data, variable,label_y, wd){
  
  p1 = graph_grp(
    data = data,
    grp = "grp",
    variable = variable,
    label_data = label_data,
    label_y = label_y,
    title = "GROUPE"
  )
  
  p2 = graph_grp(
    data = data,
    grp = "zone",
    variable = variable,
    label_data = label_data,
    label_y = label_y,
    title = "ZONE"
  )
  
  p3 = graph_grp(
    data = data,
    grp = "season",
    variable = variable,
    label_data = label_data,
    label_y = label_y,
    title = "SAISON"
  )

  plot=ggdraw()+
    draw_plot(p1, x=0, y=0, width=0.35, height=1) +
    draw_plot(p2, x=0.35,y=0, 0.45, 1) +
    draw_plot(p3, x=0.8,y=0, 0.2, 1)
  
  ggsave(
    filename = paste(wd, label_data, "_", variable, "_group_zone_saison.jpeg", sep = ""),
    plot = plot,
    device = "jpeg",
    width = 20,
    height = 5,
    units = "cm",
    dpi = 300
  )
}
