# WARNING - Generated by {fusen} from dev/flat_graph_normalised_group_zone_saison.Rmd: do not edit by hand # nolint: line_length_linter.

#' graph_normalised_group_zone_saison Title
#'
#' @param contaminant 
#' @param label_contam 
#' @param data 
#' @param label_data 
#' @param wd 
#'
#' @return 1
#' @export
#'
#' @examples
#' # graph_normalised_group_zone_saison()
GRAPH_normalised_group_zone_saison <- function(contaminant, label_contam, data,label_data, wd){

  
    contam=paste(contaminant,"_normalised_sum_ng.gdw",sep="")
    
    
    p1 = ggplot(data, aes(x=grp, y=data[,contam], color=grp, fill=grp)) + 
      geom_dotplot(binaxis='y', stackdir='center')+
      theme_bw() +
      theme(legend.position="none") +
      theme(axis.title.y = element_text(size=6), title = element_text(size=8))+
      #theme(axis.text.x=element_text(size=9, angle=45, hjust=1), legend.position="bottom") +
      stat_summary(fun = mean, geom="crossbar", size=0.5, color="darkgrey", width=.5) +
      stat_summary(fun = median, geom="crossbar", size=0.5, color="black", width=.5) +
      #guides(col=guide_legend(nrow=2)) +
      labs(title=paste(label_contam,"- GROUPE"), x=NULL, 
           y=expression(paste("Concentration normalisee (",sum()," en ng.", g[ps]^{-1},")",sep="")))
    
    
    p2 = ggplot(data, aes(x=zone, y=data[,contam], color=zone, fill=zone))+
      geom_dotplot(binaxis='y', stackdir='center')+
      theme_bw() +
      theme(legend.position="none") +
      theme(axis.text.y = element_blank(), title = element_text(size=8))+
      #theme(axis.text.x=element_text(size=9, angle=45, hjust=1), legend.position="bottom") +
      stat_summary(fun = mean, geom="crossbar", size=0.5, color="darkgrey", width=.5) +
      stat_summary(fun = median, geom="crossbar", size=0.5, color="black", width=.5) +
      #guides(col=guide_legend(nrow=2)) +
      labs(title=paste(label_contam,"- ZONE"), x=NULL, y=NULL)
    
    
    p3 = ggplot(data, aes(x=season, y=data[,contam], color=season, fill=season)) + 
      geom_dotplot(binaxis='y', stackdir='center')+
      theme_bw() +
      theme(legend.position="none") +
      theme(axis.text.y = element_blank(), title = element_text(size=8))+
      #theme(axis.text.x=element_text(size=9, angle=45, hjust=1), legend.position="bottom") +
      stat_summary(fun = mean, geom="crossbar", size=0.5, color="darkgrey", width=.5) +
      stat_summary(fun = median, geom="crossbar", size=0.5, color="black", width=.5) +
      #guides(col=guide_legend(nrow=2)) +
      labs(title=paste(label_contam,"- SAISON"), x=NULL, y=NULL)
    
    
    plot = ggdraw()+
      draw_plot(p1, x=0, y=0, width=0.35, height=1) +
      draw_plot(p2, x=0.35,y=0, 0.45, 1) +
      draw_plot(p3, x=0.8,y=0, 0.2, 1)
    
    ggsave(filename = paste(wd,label_data,"_normalised_",contaminant,".jpeg",sep=""),
           plot = plot,device = "jpeg",width = 20,height = 5, units = "cm",dpi=300)
    
}

