# WARNING - Generated by {fusen} from dev/flat_stat_occurence.Rmd: do not edit by hand # nolint: line_length_linter.

#' occ Fonction de calcul de la fréquence d'occurence (concentration != 0) parmi les échantillons analysés (non NA)
#'
#' @param vector Vecteur contenant des valeurs de contamination ou des valeurs manquantes
#'
#' @return value Proportion de valeurs non nulles parmis 
#' @export
#'
#' @examples
#'  vec <- c(0, 1, 5, NA)
#'  occ(vector = vec)
occ = function(vector){
  length(which(na.omit(vector)!=0)) / length(na.omit(vector))
}
