# WARNING - Generated by {fusen} from dev/flat_diet_study.Rmd: do not edit by hand # nolint: line_length_linter.

#' Occurrence (%number over number of all preys) of each prey species in a stomac content dataset
#' 
#' @param data_stomac Raw data stomach content with number of a given prey (ScientificName_accepted) in all the tractus (Nbr.total.tractus) for related tag fish (N.poissons).
#'
#' @return dataframe Prey species, Total proportion in all tractus
#' 
#' @export
#' @examples
#' library(chopin.project)
#' occurence(stomac_soles)
occurence = function(data_stomac){
  
  res_occurence = c()
  for(s in levels(data_stomac$ScientificName_accepted) ){
    res_occurence = c(res_occurence,
                      length(data_stomac[which(data_stomac$ScientificName_accepted==s),]$N.poissons))
  }
  res_occurence = res_occurence/length(table(data_stomac$N.poissons)[which(table(data_stomac$N.poissons)!=0)])*100
  res_occurence = data.frame(levels(data_stomac$ScientificName_accepted), res_occurence)
  
  return(res_occurence)
}
