# WARNING - Generated by {fusen} from dev/flat_diet_study.Rmd: do not edit by hand # nolint: line_length_linter.

#' Piechart of diet for a group of soles
#' 
#' with type of color by taxon
#' 
#' @return
#' 
#' @export
#' @examples
#' library(chopin.project)
#' library(tidyverse)
#' library(scales)
#'
#' res_G0_emb_juin = get_res_diet(
#'   main = "G0 Embouchure printemps",
#'   grp = stomac_soles[which(
#'     stomac_soles$secteur == "Embouchure" &
#'       stomac_soles$espèce.stade == "Sole G0" &
#'       stomac_soles$Campagne == "Print-17"
#'   ), ],
#'   min_abond = 0.1,  min_occur = 0.1
#' )
#' piechart_diet(res_pie = res_G0_emb_juin$`med %abun`)
piechart_diet = function(res_pie){

  res_pie$col=rep.int(NA,times = length(res_pie$species))
  for(i in 1:dim(res_pie)[1]){
    res_pie$col[i] = list_taxon$col_species[which(list_taxon$species==as.character(res_pie$species[i]))]
  }
  
  # intersect(as.character(res_pie$species), list_taxon$species)

  res_pie <- res_pie %>%
    arrange(desc(species)) %>%
    mutate(prop = tx.abun / sum(res_pie$tx.abun) *100) %>%
    mutate(ypos = cumsum(prop)- 0.5*prop )

  bp<- ggplot(res_pie, aes(x="", y=tx.abun, fill=species))+
    geom_bar(width = 1, stat = "identity", color="white")
  pie <- bp + coord_polar("y", start=0)
  blank_theme <- theme_minimal()+
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.border = element_blank(),
      panel.grid=element_blank(),
      axis.ticks = element_blank(),
      plot.title=element_text(size=12, face="bold")
    )
  pie +  
    scale_fill_manual(values=res_pie$col[order(res_pie$species)]) +
    blank_theme+theme(axis.text.x=element_blank()) +
    labs(fill="Espèces") +
    geom_text(aes(y = ypos,
                  label = percent(res_pie$tx.abun/100, accuracy = 1)),
                  size=4)

}
