# WARNING - Generated by {fusen} from dev/flat_test_effect.Rmd: do not edit by hand # nolint: line_length_linter.

#' test_effect Test l'effet d'une variable qualitative sur une variable quantitative
#' 
#' Lance les tests suivants :
#' - Kruskal-Wallis Rank Sum Test
#' - Pairwise Wilcoxon Rank Sum Tests
#' - Wilcoxon Rank Sum and Signed Rank Tests
#' 
#' @param dataset dataframe contenant les deux variables à étudier
#' @param variable vecteur du dataframe - variable quantitative
#' @param factor vecteur du dataframe - variable qualitative
#'
#' @return 1
#' @export
#'
#' @examples
#' test_effect(dataset = iris, variable = "Sepal.Length", factor = "Species")
test_effect = function(dataset, variable, factor) {
  print(paste(variable, factor, sep = " / "))
  print(kruskal.test(dataset[, variable], g = dataset[, factor]))
  print(pairwise.wilcox.test(dataset[, variable], g = dataset[, factor]))
  print(wilcox.test(dataset[, variable], g = dataset[, factor]))
}
